from enum import Enum

class Task(Enum):
    """Enum for task type."""
    SAMPLE_MATCHING = "Source matching (1 source img per subject, N reference images to match)"
    CLUSTERING = "Clustering (Unknown number of subjects gathered in a single folder)"

class StatusLogMessage(Enum):
    """Enum for status message type."""
    START = "Welcome to Photo Matcher!\nTo run source matching, select the source and reference image folders. Make sure that source folder has 1 image per subject, and reference folder has N images to match. For each subject, a folder will be created to the output path and images will be copied to the respective subject folders."
    SAMPLE_MATCHING = "Tips: To run source matching, select the source and reference image folders. Make sure that source folder has 1 image per subject, and reference folder has N images to match. For each subject, a folder will be created to the output path and images will be copied to the respective subject folders."
    CLUSTERING = "Tips: To run clustering, select the folder containing images to cluster. All images will be recursively picked up. The number of clusters will be automatically determined based on the number of images found. For each cluster, folders will be created to the output path and images will be copied to the respective cluster folders."

class ErrorMessage(Enum):
    PATH_NOT_SELECTED = "Error, Please select all required valid paths."
    SOURCE_FOLDER_EMPTY = "Error, Please make sure that there are image files in the source folder."
    REFERENCE_FOLDER_EMPTY = "Error, Please make sure that there are image files in the reference folder."


class ClusteringAlgorithm(Enum):
    """Enum for clustering algorithm."""
    DBSCAN = "DBSCAN"
    OPTICS = "OPTICS"
    HDBSCAN = "HDBSCAN"

IMAGE_EXTENSION = [
    "ase",
    "art",
    "bmp",
    "blp",
    "cd5",
    "cit",
    "cpt",
    "cr2",
    "cut",
    "dds",
    "dib",
    "djvu",
    "egt",
    "exif",
    "gif",
    "gpl",
    "grf",
    "icns",
    "ico",
    "iff",
    "jng",
    "jpeg",
    "jpg",
    "jfif",
    "jp2",
    "jps",
    "lbm",
    "max",
    "miff",
    "mng",
    "msp",
    "nef",
    "nitf",
    "ota",
    "pbm",
    "pc1",
    "pc2",
    "pc3",
    "pcf",
    "pcx",
    "pdn",
    "pgm",
    "PI1",
    "PI2",
    "PI3",
    "pict",
    "pct",
    "pnm",
    "pns",
    "ppm",
    "psb",
    "psd",
    "pdd",
    "psp",
    "px",
    "pxm",
    "pxr",
    "qfx",
    "raw",
    "rle",
    "sct",
    "sgi",
    "rgb",
    "int",
    "bw",
    "tga",
    "tiff",
    "tif",
    "vtf",
    "xbm",
    "xcf",
    "xpm",
    "3dv",
    "amf",
    "ai",
    "awg",
    "cgm",
    "cdr",
    "cmx",
    "dxf",
    "e2d",
    "egt",
    "eps",
    "fs",
    "gbr",
    "odg",
    "svg",
    "stl",
    "vrml",
    "x3d",
    "sxd",
    "v2d",
    "vnd",
    "wmf",
    "emf",
    "art",
    "xar",
    "png",
    "webp",
    "jxr",
    "hdp",
    "wdp",
    "cur",
    "ecw",
    "iff",
    "lbm",
    "liff",
    "nrrd",
    "pam",
    "pcx",
    "pgf",
    "sgi",
    "rgb",
    "rgba",
    "bw",
    "int",
    "inta",
    "sid",
    "ras",
    "sun",
    "tga",
    "heic",
    "heif",
]
