[build-system]
requires = ["hatchling", "cmake", "cx_Freeze"]
build-backend = "hatchling.build"

[project]
name = "PhotolinkML"
version = "0.0.1" # should be dynamic later on
description = "Photolink application"
requires-python = ">=3.9, <3.12"
authors = [
    { name = "Philip Cho", email = "chophilip21@gmail.com" },
    { name = "Alinstein Jose", email = "alinsteinjose@gmail.com" },
]

[project.optional-dependencies]
devel = [
    "pyside6",
    "scikit-learn",
    "pycairo",
    "faiss-cpu==1.8.0",
    "packaging",
    "hdbscan",
    "opencv-python",
    "pyinstaller",
    "loguru",
]

[tool.hatch.build.targets.wheel]
packages = ["src/photolink"]

[tool.hatch.build.targets.sdist]
include = [
    "helpers/requirements/devel.txt",
    "helpers/requirements/test.txt",
    "README.md",
]